services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: password-vault-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: password-vault
    volumes:
      - mongodb_data:/data/db
    networks:
      - password-vault-network

  # Password Vault Application
  app:
    build: .
    container_name: password-vault-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/password-vault?authSource=admin
      NEXTAUTH_SECRET: your-super-secret-jwt-key-change-this-in-production
      NEXTAUTH_URL: http://localhost:3000
    depends_on:
      - mongodb
    networks:
      - password-vault-network
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongodb_data:

networks:
  password-vault-network:
    driver: bridge
